fn main() {
    // print::it_work();
    // primitive::it_works();
    // custom_type::it_works();
    // variable::it_works();
    // types::it_works();
    // conversion::it_work();
    // expression::it_works();
    // destructure::it_works();
    // function::it_works();
    // cfg::it_works();
    // generic::it_works();
    // borrow::it_works();
    // lifetime::it_works();
    // trait_mod::it_works();
    // macros::it_works();
    // result::it_works();
    collections::it_works();
    thread::it_works();
}
mod custom_type;
mod primitive;
mod print;
mod variable;
mod types;
mod conversion;
mod expression;
mod destructure;
mod function;
mod cfg;
mod generic;
mod borrow;
mod lifetime;
mod trait_mod;
mod macros;
mod result;
mod collections;
mod thread;